apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xyqd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0021-tenant/ci1t-43256-0021-app/devfile-sample-xyqd@sha256:4fa5dae10fa42e6a919297ade8f64f8196cc576c40bb63ca76cf92e615b47067
        name: my-nodejs
        resources: {}
status: {}
