apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xyqd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xyqd
    app.kubernetes.io/part-of: ci1t-43256-0021-app
  name: devfile-sample-xyqdedue
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-xyqd
    weight: null
status: {}
